# Generated by Django 4.2 on 2025-03-25 12:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0008_alter_tag_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='art',
            old_name='type',
            new_name='style',
        ),
        migrations.RemoveField(
            model_name='art',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='deviant',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='oficial',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='twitter',
        ),
        migrations.AddField(
            model_name='artist',
            name='is_professional',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('comment', models.TextField()),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.art')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.artist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, 'Penciler'), (2, 'Colors'), (3, 'Sculptor'), (4, 'Designer')])),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.art')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.artist')),
            ],
        ),
        migrations.AddField(
            model_name='art',
            name='artists',
            field=models.ManyToManyField(through='portfolio.Artwork', to='portfolio.artist'),
        ),
        migrations.AddField(
            model_name='art',
            name='ratings',
            field=models.ManyToManyField(related_name='ratings', through='portfolio.Rating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=32)),
                ('link', models.URLField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.artist')),
            ],
            options={
                'unique_together': {('artist', 'network')},
            },
        ),
    ]
