# Generated by Django 4.2 on 2025-03-25 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0009_rename_type_art_style_remove_art_artist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='ratings',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='art',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='artist',
        ),
        migrations.AddField(
            model_name='artwork',
            name='ratings',
            field=models.ManyToManyField(related_name='ratings', through='portfolio.Rating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='artwork',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portfolio.artwork'),
            preserve_default=False,
        ),
    ]
