# Generated by Django 4.2 on 2025-03-25 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0010_remove_art_ratings_remove_rating_art_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='ratings',
        ),
        migrations.AddField(
            model_name='art',
            name='ratings',
            field=models.ManyToManyField(related_name='ratings', through='portfolio.Rating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='art',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portfolio.art'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'art')},
        ),
        migrations.RemoveField(
            model_name='rating',
            name='artwork',
        ),
    ]
