# Generated by Django 4.2 on 2025-04-14 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0011_remove_artwork_ratings_art_ratings_rating_art_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='ratings',
            field=models.ManyToManyField(related_name='user_ratings', through='portfolio.Rating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rating',
            name='art',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='portfolio.art'),
        ),
    ]
